### get orders period
GET localhost:8080/api/order/customer/orders?start=2024-08-25&end=2024-08-30&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDg0MjEwNywiZXhwIjoxNzI0OTI4NTA3fQ.UnTFBB4YTNTF-k-CUW5XzkkK2LRpuK0YfRiyJfcguZ3GNIcre6FybGm8Xw_iWs4j9Dp1cxWjeFb-dwYyDtAV0g

### get order detail
GET localhost:8080/api/order/customer/order?id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDkxMDY0MiwiZXhwIjoxNzI0OTk3MDQyfQ.8ugAVQsyLnI0W1Bm1NK3tleEmkW0CmvaL8JlnpYlgTFCZ36yY5fjYsrxtU0UAC_tPflgxGE0LE-L-UILhGhMYg

### get orders period
GET localhost:8080/api/order/customer?start=2024-08-25&end=2024-08-29&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDkxMDY0MiwiZXhwIjoxNzI0OTk3MDQyfQ.8ugAVQsyLnI0W1Bm1NK3tleEmkW0CmvaL8JlnpYlgTFCZ36yY5fjYsrxtU0UAC_tPflgxGE0LE-L-UILhGhMYg

### cancel order
GET localhost:8080/api/order/customer/order/cancel?id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDg0MjEwNywiZXhwIjoxNzI0OTI4NTA3fQ.UnTFBB4YTNTF-k-CUW5XzkkK2LRpuK0YfRiyJfcguZ3GNIcre6FybGm8Xw_iWs4j9Dp1cxWjeFb-dwYyDtAV0g

### get orders by store
GET localhost:8080/api/order/seller/1?start=2024-08-25&end=2024-08-29&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ2NzE5MDcsImV4cCI6MTcyNDc1ODMwN30.cLtcA32vYv4eUcwxKzlYsStT-uZYmIViBonSEKp9qid7OKoBWDWYQXPeN-QPGJxxT2sFm5cxIfnsIVCZivvX3g

### request orders refund
PATCH localhost:8080/api/order/customer/refund/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDg0MjEwNywiZXhwIjoxNzI0OTI4NTA3fQ.UnTFBB4YTNTF-k-CUW5XzkkK2LRpuK0YfRiyJfcguZ3GNIcre6FybGm8Xw_iWs4j9Dp1cxWjeFb-dwYyDtAV0g

### orders refund approve
PATCH localhost:8080/api/order/seller/refund/approve/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ2NzE5MDcsImV4cCI6MTcyNDc1ODMwN30.cLtcA32vYv4eUcwxKzlYsStT-uZYmIViBonSEKp9qid7OKoBWDWYQXPeN-QPGJxxT2sFm5cxIfnsIVCZivvX3g

### orders refund reject
PATCH localhost:8080/api/order/seller/refund/reject/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ2NzE5MDcsImV4cCI6MTcyNDc1ODMwN30.cLtcA32vYv4eUcwxKzlYsStT-uZYmIViBonSEKp9qid7OKoBWDWYQXPeN-QPGJxxT2sFm5cxIfnsIVCZivvX3g
