### get orders period
GET localhost:8080/api/order/customer/orders?start=2024-08-25&end=2024-09-30&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNTg4NDc4MSwiZXhwIjoxNzI1OTcxMTgxfQ.blRUgJ4Ymy-QTdVZcbZSMiDoKUAS6Piv45nyiVJqhGtF39Pccrn07GFDRFvCms7-XqAf4bXlY0xVTJuI1N070Q

### get order detail
GET localhost:8080/api/order/customer/order?id=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNTg4NDc4MSwiZXhwIjoxNzI1OTcxMTgxfQ.blRUgJ4Ymy-QTdVZcbZSMiDoKUAS6Piv45nyiVJqhGtF39Pccrn07GFDRFvCms7-XqAf4bXlY0xVTJuI1N070Q

### get orders period
GET localhost:8080/api/order/customer/orders?start=2024-08-25&end=2024-09-29&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNTg4NDc4MSwiZXhwIjoxNzI1OTcxMTgxfQ.blRUgJ4Ymy-QTdVZcbZSMiDoKUAS6Piv45nyiVJqhGtF39Pccrn07GFDRFvCms7-XqAf4bXlY0xVTJuI1N070Q

### cancel order
DELETE localhost:8080/api/order/customer/order/cancel?id=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNTg4NDc4MSwiZXhwIjoxNzI1OTcxMTgxfQ.blRUgJ4Ymy-QTdVZcbZSMiDoKUAS6Piv45nyiVJqhGtF39Pccrn07GFDRFvCms7-XqAf4bXlY0xVTJuI1N070Q

### get orders by store
GET localhost:8080/api/order/seller/orders?storeId=2&start=2024-08-25&end=2024-09-29&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjU4ODUxNDQsImV4cCI6MTcyNTk3MTU0NH0.SmakOhDO80lrZ9ItMu5YoqkadXXjleY25JOZx4-CsXlvfilBQOShgqHZAsN61s5K32RqJj1cFm3u9Opp4Pt8RA

### request orders refund
PATCH localhost:8080/api/order/customer/refund/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNTg4NDc4MSwiZXhwIjoxNzI1OTcxMTgxfQ.blRUgJ4Ymy-QTdVZcbZSMiDoKUAS6Piv45nyiVJqhGtF39Pccrn07GFDRFvCms7-XqAf4bXlY0xVTJuI1N070Q

### orders refund approve
PATCH localhost:8080/api/order/seller/refund/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjU4ODUxNDQsImV4cCI6MTcyNTk3MTU0NH0.SmakOhDO80lrZ9ItMu5YoqkadXXjleY25JOZx4-CsXlvfilBQOShgqHZAsN61s5K32RqJj1cFm3u9Opp4Pt8RA

{
  "id": 3,
  "date": "2024-09-06"
}

### orders refund reject
PATCH localhost:8080/api/order/seller/refund/reject/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjU4ODUxNDQsImV4cCI6MTcyNTk3MTU0NH0.SmakOhDO80lrZ9ItMu5YoqkadXXjleY25JOZx4-CsXlvfilBQOShgqHZAsN61s5K32RqJj1cFm3u9Opp4Pt8RA

###
POST localhost:8080/api/order/seller/settlement?start=2024-09-01&end=2024-09-30
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjU4ODUxNDQsImV4cCI6MTcyNTk3MTU0NH0.SmakOhDO80lrZ9ItMu5YoqkadXXjleY25JOZx4-CsXlvfilBQOShgqHZAsN61s5K32RqJj1cFm3u9Opp4Pt8RA
