### get orders period
GET localhost:8080/api/order/customer?start=2024-08-25&end=2024-08-29&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY0OTM1NCwiZXhwIjoxNzI0NzM1NzU0fQ.Q08XzNP_WUY-b_HIfkEjcwyjVQgiushz9MyLZD3hG0Mg3mQDCJeykhk_dPoCE16PdQs502ztgRDfrkiOiDIp6A

### get orders by store
GET localhost:8080/api/order/seller/1?start=2024-08-25&end=2024-08-29&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ2NTUxNzIsImV4cCI6MTcyNDc0MTU3Mn0.k_ukeiS35_gIrFjk_vJYLEumbNaC6ZgsnCYStInfxFlNW9EsYj_5FNRE85nuI6C14FzE4FHrbnlfIn2KqhHdCg

### request orders refund
PATCH localhost:8080/api/order/customer/refund/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY0OTM1NCwiZXhwIjoxNzI0NzM1NzU0fQ.Q08XzNP_WUY-b_HIfkEjcwyjVQgiushz9MyLZD3hG0Mg3mQDCJeykhk_dPoCE16PdQs502ztgRDfrkiOiDIp6A

### orders refund approve
PATCH localhost:8080/api/order/seller/refund/approve/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ2NTUxNzIsImV4cCI6MTcyNDc0MTU3Mn0.k_ukeiS35_gIrFjk_vJYLEumbNaC6ZgsnCYStInfxFlNW9EsYj_5FNRE85nuI6C14FzE4FHrbnlfIn2KqhHdCg

### orders refund reject
PATCH localhost:8080/api/order/seller/refund/reject/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ2NTUxNzIsImV4cCI6MTcyNDc0MTU3Mn0.k_ukeiS35_gIrFjk_vJYLEumbNaC6ZgsnCYStInfxFlNW9EsYj_5FNRE85nuI6C14FzE4FHrbnlfIn2KqhHdCg
