### signup member
POST http://localhost:8080/api/member/signup/seller
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "name": "user1",
  "password": "qwerty",
  "phone": "01012345678",
  "roles": ["ROLE_SELLER"]
}


### signin member
POST http://localhost:8080/api/member/signin/seller
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "qwerty"
}

### signup member
POST http://localhost:8080/api/member/signup/customer
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "name": "user2",
  "password": "qwerty",
  "phone": "01012345678",
  "roles": ["ROLE_CUSTOMER"]
}

### signin member
POST http://localhost:8080/api/member/signin/customer
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "qwerty"
}

### charge balance
POST http://localhost:8080/api/member/customer/charge
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "email": "user2@gmail.com",
  "amount": 1000
}

### follow store
POST http://localhost:8080/api/member/customer/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "storeId": 1
}

### follow store
POST http://localhost:8080/api/member/customer/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "storeId": 3
}

### unfollow store
POST http://localhost:8080/api/member/customer/unfollow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "storeId": 2
}

### get follow stores
GET http://localhost:8080/api/member/customer/stores?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg


### heart item
POST http://localhost:8080/api/member/customer/heart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "itemId": 4
}

### heart item
POST http://localhost:8080/api/member/customer/heart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "itemId": 5
}

### unheart item
POST http://localhost:8080/api/member/customer/unheart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg

{
  "itemId": 4
}

### get heart items
GET http://localhost:8080/api/member/customer/items?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY2ODkxNywiZXhwIjoxNzI0NzU1MzE3fQ.GTbd6_5dw70i2A4JpMU1iOhMtofpeA8UQATIy6TE6D7Rq-SRBlFPs6t0Jv9ta21x2prRRv22nWFQ7W9Zw9s7zg
