### signup member
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "name": "user1",
  "password": "qwerty",
  "phone": "01012345678",
  "roles": ["ROLE_SELLER"]
}


### signin member
POST http://localhost:8080/api/member/signin
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "qwerty"
}

### signup member
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "name": "user2",
  "password": "qwerty",
  "phone": "01012345678",
  "roles": ["ROLE_CUSTOMER"]
}

### signin member
POST http://localhost:8080/api/member/signin
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "qwerty"
}

### charge balance
POST http://localhost:8080/api/member/charge
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcxNzE1OCwiZXhwIjoxNzIzODAzNTU4fQ.yuHKjzxX4Y3Zm99IKF_fkL2uJaXtxEg_iEatfis7-Qh5AXa7E5QrMo67OHUZnc947kMywLXcdtvz2YHpDFKRiA

{
  "email": "user2@gmail.com",
  "amount": 1000
}

### follow store
POST http://localhost:8080/api/member/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcyMzUzMywiZXhwIjoxNzIzODA5OTMzfQ.Yk2Dt0KLHMQ2zJ8c4zK_1Iyp1XcUOzxPdFHlpGCE471onDkWPnKqWQwEq2zAqS3k9Ic4wDWwtPb8Llpp32iS6Q

{
  "storeId": 1
}

### follow store
POST http://localhost:8080/api/member/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcyMzUzMywiZXhwIjoxNzIzODA5OTMzfQ.Yk2Dt0KLHMQ2zJ8c4zK_1Iyp1XcUOzxPdFHlpGCE471onDkWPnKqWQwEq2zAqS3k9Ic4wDWwtPb8Llpp32iS6Q

{
  "storeId": 3
}

### unfollow store
POST http://localhost:8080/api/member/unfollow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzU1NjkwOSwiZXhwIjoxNzIzNjQzMzA5fQ.NRDq_KBfJR9FRgi6Rd1IIcKOaHZfJVUruohUAOphhdH4PQ_9PJstTZqof6bAPhhWYy-j87UnjhhY9GnrdzFI7Q

{
  "storeId": 2
}

### get follow stores
GET http://localhost:8080/api/member/stores?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcyMzUzMywiZXhwIjoxNzIzODA5OTMzfQ.Yk2Dt0KLHMQ2zJ8c4zK_1Iyp1XcUOzxPdFHlpGCE471onDkWPnKqWQwEq2zAqS3k9Ic4wDWwtPb8Llpp32iS6Q


### heart item
POST http://localhost:8080/api/member/heart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcyMzUzMywiZXhwIjoxNzIzODA5OTMzfQ.Yk2Dt0KLHMQ2zJ8c4zK_1Iyp1XcUOzxPdFHlpGCE471onDkWPnKqWQwEq2zAqS3k9Ic4wDWwtPb8Llpp32iS6Q

{
  "itemId": 4
}

### heart item
POST http://localhost:8080/api/member/heart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjM3MDM2MjQsImV4cCI6MTcyMzc5MDAyNH0.EIA7kKDtF8SH8fq7aZTBxzSys-KqZXi5bUW--bZW28UcgF5The7UqdFFtIg10e5Eare9sMjXu4NFR-KhTCz4vQ

{
  "itemId": 5
}

### unheart item
POST http://localhost:8080/api/member/unheart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcyMzUzMywiZXhwIjoxNzIzODA5OTMzfQ.Yk2Dt0KLHMQ2zJ8c4zK_1Iyp1XcUOzxPdFHlpGCE471onDkWPnKqWQwEq2zAqS3k9Ic4wDWwtPb8Llpp32iS6Q

{
  "itemId": 4
}

### get heart items
GET http://localhost:8080/api/member/items?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzcyMzUzMywiZXhwIjoxNzIzODA5OTMzfQ.Yk2Dt0KLHMQ2zJ8c4zK_1Iyp1XcUOzxPdFHlpGCE471onDkWPnKqWQwEq2zAqS3k9Ic4wDWwtPb8Llpp32iS6Q
