### cart 주문
POST localhost:8080/api/store/cart/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNDY0OTM1NCwiZXhwIjoxNzI0NzM1NzU0fQ.Q08XzNP_WUY-b_HIfkEjcwyjVQgiushz9MyLZD3hG0Mg3mQDCJeykhk_dPoCE16PdQs502ztgRDfrkiOiDIp6A

{
  "customerId": 2,
  "items": [
    {
      "id": 6,
      "storeId": 2,
      "sellerId": 1,
      "storeName": "달달구리해닮",
      "name": "샹티크림끌레오르",
      "options": [
        {
          "id": 11,
          "name": "얼그레이샹티크림 끌레오르",
          "quantity": 2,
          "price": 26000
        }
      ]
    },
    {
      "id": 1,
      "storeId": 1,
      "sellerId": 1,
      "storeName": "수제청 청이",
      "name": "혈관청소부 비트(ABC)건강/디톡스/다이어트주스 10병",
      "options": [
        {
          "id": 1,
          "name": "비트(ABC)주스 200ml 10병",
          "quantity": 5,
          "price": 32000
        }
      ]
    }
  ],
  "messages": [],
  "totalPrice": 212000
}