### register store
POST http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ4MjUwNzUsImV4cCI6MTcyNDkxMTQ3NX0.LBT7UNq9e4nA0ut52u_DD_D5Ev7CNB2cZOgCvlSyVTbUf3pQs7SsmVQQcRYQ25miAlW-0M3BPh882aZ0HVAlyg

{
  "name": "디디얌",
  "description": "디디얌 베이커리&디저트",
  "thumbnailUrl": "https://디디얌.png"
}

### register store
POST http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ4MjUwNzUsImV4cCI6MTcyNDkxMTQ3NX0.LBT7UNq9e4nA0ut52u_DD_D5Ev7CNB2cZOgCvlSyVTbUf3pQs7SsmVQQcRYQ25miAlW-0M3BPh882aZ0HVAlyg

{
  "name": "달달구리해닮",
  "description": "해남으로 귀농해서 농부가 되었습니다",
  "thumbnailUrl": "https://해닮.png"
}

### register store
POST http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ4MjUwNzUsImV4cCI6MTcyNDkxMTQ3NX0.LBT7UNq9e4nA0ut52u_DD_D5Ev7CNB2cZOgCvlSyVTbUf3pQs7SsmVQQcRYQ25miAlW-0M3BPh882aZ0HVAlyg

{
  "name": "바스켓베이커리",
  "description": "#노밀가루, #노정제설탕, #노글루텐",
  "thumbnailUrl": "https://바스켓.png"
}

### update store
PUT http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "id": 4,
  "name": "바스켓베이커리 수정",
  "description": "#노밀가루, #노정제설탕, #노글루텐",
  "thumbnailUrl": "https://바스켓.png"
}

### delete store
PATCH http://localhost:8080/api/store?id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw
