### search store by keyword
GET http://localhost:8080/api/store/search?keyword=해닮&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

### search store by keyword with follow order
GET http://localhost:8080/api/store/search/follow?keyword=&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

### search store by keyword with follow order
GET http://localhost:8080/api/store/search/detail?id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw
