### register store
POST http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQxMzI0NzEsImV4cCI6MTcyNDIxODg3MX0.jAmWWi5Ah7FuAGNoGvezzHD6vo1OxrWzjvWs6Btbf1b7VAAzZ3TYPCvtelMOCjKUG309g9twBPDjiLHhX5lhrg

{
  "name": "수제청 청이",
  "description": "신선한 과일과 채소에 정성을 더한 핸드메이드 과일청&주스",
  "thumbnailUrl": "https://청이.png"
}

### register store
POST http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQxMzI0NzEsImV4cCI6MTcyNDIxODg3MX0.jAmWWi5Ah7FuAGNoGvezzHD6vo1OxrWzjvWs6Btbf1b7VAAzZ3TYPCvtelMOCjKUG309g9twBPDjiLHhX5lhrg

{
  "name": "달달구리해닮",
  "description": "해남으로 귀농해서 농부가 되었습니다",
  "thumbnailUrl": "https://해닮.png"
}

### register store
POST http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQxMzI0NzEsImV4cCI6MTcyNDIxODg3MX0.jAmWWi5Ah7FuAGNoGvezzHD6vo1OxrWzjvWs6Btbf1b7VAAzZ3TYPCvtelMOCjKUG309g9twBPDjiLHhX5lhrg

{
  "name": "바스켓베이커리",
  "description": "#노밀가루, #노정제설탕, #노글루텐",
  "thumbnailUrl": "https://바스켓.png"
}

### update store
PUT http://localhost:8080/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjM2MTcxMDEsImV4cCI6MTcyMzcwMzUwMX0.dJOIOY8_tJQbit9qGj6ts6Gnt66J9mKanjDrxVn_eqoYbmHWeXZJZcuKyVDhxN_X5dCObUUgbPccNEJEVz10_A

{
  "id": 4,
  "name": "바스켓베이커리 수정",
  "description": "#노밀가루, #노정제설탕, #노글루텐",
  "thumbnailUrl": "https://바스켓.png"
}

### delete store
PATCH http://localhost:8080/api/store?id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQxMzI0NzEsImV4cCI6MTcyNDIxODg3MX0.jAmWWi5Ah7FuAGNoGvezzHD6vo1OxrWzjvWs6Btbf1b7VAAzZ3TYPCvtelMOCjKUG309g9twBPDjiLHhX5lhrg
