### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 1,
  "name": "혈관청소부 비트(ABC)건강/디톡스/다이어트주스 10병",
  "thumbnailUrl": "https://비트.png",
  "description": "사과1:당근1:비트1/3 황금비율의 주스",
  "descriptionUrl": "https://비트.png",
  "options": [
    {
      "name": "비트(ABC)주스 200ml 10병",
      "quantity": 10,
      "price": 32000
    },
    {
      "name": "비트(ABC)주스 200ml 20병",
      "quantity": 10,
      "price": 64000
    },
    {
      "name": "비트(ABC)주스 200ml 30병",
      "quantity": 10,
      "price": 96000
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 1,
  "name": "건강음료 맷돌호박식혜 500ml 4병",
  "thumbnailUrl": "https://맷돌호박식혜.png",
  "description": "믿을 수 있는 재료와 전통방식 그대로 정성을 더하여 만든 호박 식혜",
  "descriptionUrl": "https://맷돌호박식혜.png",
  "options": [
    {
      "name": "호박식혜 500ml 4병",
      "quantity": 10,
      "price": 20000
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 1,
  "name": "자몽착즙청 자몽에이드 500ml",
  "thumbnailUrl": "https://자몽착즙청.png",
  "description": "자몽의 알맹이만 착즙하여 만든 리얼자몽착즙청!",
  "descriptionUrl": "https://자몽착즙청.png",
  "options": [
    {
      "name": "자몽착즙청 500ml",
      "quantity": 10,
      "price": 20000
    },
    {
      "name": "레몬착즙청 500ml",
      "quantity": 10,
      "price": 20000
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 2,
  "name": "꿀고구마 티그레",
  "thumbnailUrl": "https://티그레.png",
  "description": "꿀고구마티그레 대체당으로 만든4종 얼그레이,흑임자,오리지널,피스타치오",
  "descriptionUrl": "https://티그레.png",
  "options": [
    {
      "name": "6개세트",
      "quantity": 10,
      "price": 17000
    },
    {
      "name": "9개세트",
      "quantity": 10,
      "price": 21000
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 2,
  "name": "카라멜버터샌드쿠키세트",
  "thumbnailUrl": "https://카라멜버터샌드쿠키세트.png",
  "description": "부드럽고 고급스러운 파트슈크레 쿠키 사이로 겹겹히 올라간. 부드러운 버터와 수제로만든 피넛프랄리네카라멜, 쏠티드카라멜",
  "descriptionUrl": "https://카라멜버터샌드쿠키세트.png",
  "options": [
    {
      "name": "쏠티드카라멜버터샌드10세트",
      "quantity": 10,
      "price": 27500
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 2,
  "name": "샹티크림끌레오르",
  "thumbnailUrl": "https://샹티크림끌레오르.png",
  "description": "식이섬유가 풍부한 베니고구마와 아몬드푸들가득 넣어만든 끌레오르와 부드럽고 고급스러운 샹티크림이 만나 귀여운 쿠키케이크",
  "descriptionUrl": "https://샹티크림끌레오르.png",
  "options": [
    {
      "name": "보늬밤샹티크림 끌레오르",
      "quantity": 10,
      "price": 26000
    },
    {
      "name": "얼그레이샹티크림 끌레오르",
      "quantity": 10,
      "price": 26000
    },
    {
      "name": "블루베리샹티크림 끌레오르",
      "quantity": 10,
      "price": 26000
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 3,
  "name": "노밀가루,글루텐프리 바스켓베이커리 스콘",
  "thumbnailUrl": "https://스콘.png",
  "description": "글루텐프리 베이킹파우더 사용",
  "descriptionUrl": "https://스콘.png",
  "options": [
    {
      "name": "무화과와인",
      "quantity": 10,
      "price": 5200
    },
    {
      "name": "황치즈",
      "quantity": 10,
      "price": 5200
    },
    {
      "name": "밀크",
      "quantity": 10,
      "price": 4500
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 3,
  "name": "노밀가루 바스켓베이커리 파운드케이크",
  "thumbnailUrl": "https://파운드케이크.png",
  "description": "글루텐프리 베이킹파우더 사용",
  "descriptionUrl": "https://파운드케이크.png",
  "options": [
    {
      "name": "블루베리코코넛",
      "quantity": 10,
      "price": 6200
    },
    {
      "name": "플레인",
      "quantity": 10,
      "price": 5500,
      "discount":700
    },
    {
      "name": "얼그레이(트와이닝)",
      "quantity": 10,
      "price": 6200
    }
  ]
}

### create item
POST http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjQ1NjgxMTcsImV4cCI6MTcyNDY1NDUxN30.QMKfdGM59wV-T2KFTJZWzyop6yPwFDJUqxiYTxdIXUdpOJ--8j8bRgtN197vv2GUZpuzs3J0_h1_HyFUobNhbw

{
  "storeId": 3,
  "name": "노밀가루 바스켓베이커리 쌀피칸브라우니",
  "thumbnailUrl": "https://쌀피칸브라우니.png",
  "description": "글루텐프리 베이킹파우더 사용",
  "descriptionUrl": "https://쌀피칸브라우니.png",
  "options": [
    {
      "name": "쌀피칸브라우니",
      "quantity": 10,
      "price": 5500
    }
  ]
}

### update item
PUT http://localhost:8080/api/store/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjM3MDM2MjQsImV4cCI6MTcyMzc5MDAyNH0.EIA7kKDtF8SH8fq7aZTBxzSys-KqZXi5bUW--bZW28UcgF5The7UqdFFtIg10e5Eare9sMjXu4NFR-KhTCz4vQ

{
  "id": 8,
  "storeId": 3,
  "name": "노밀가루 바스켓베이커리 파운드케이크",
  "thumbnailUrl": "https://파운드케이크.png",
  "description": "https://파운드케이크.png",
  "descriptionUrl": "https://파운드케이크.png",
  "options": [
    {
      "name": "블루베리코코넛",
      "quantity": 10,
      "regularPrice": 6200,
      "discount": 777700
    },
    {
      "name": "플레인",
      "quantity": 10,
      "regularPrice": 5500,
      "discount":700
    },
    {
      "name": "얼그레이(트와이닝)",
      "quantity": 10,
      "regularPrice": 6200,
      "discount": 500
    }
  ]
}

### delete item
DELETE http://localhost:8080/api/store/item?id=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1NFTExFUiJdLCJpYXQiOjE3MjM3MDM2MjQsImV4cCI6MTcyMzc5MDAyNH0.EIA7kKDtF8SH8fq7aZTBxzSys-KqZXi5bUW--bZW28UcgF5The7UqdFFtIg10e5Eare9sMjXu4NFR-KhTCz4vQ
