server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjuuujh/dessert-msa-config # 설정파일 있는 git 주소
          default-label: master # 설정파일 있는 git branch
        encrypt:
          enabled: true

eureka: # eureka client 등록
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

encrypt:
  key-store:
    alias: encryptionKey
    password: dessertEncryptionKey
    location: encryptionKey.jks
#    location: file:/encryptionKey.jks

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
