### get config
GET http://localhost:8888/api-gateway/dev

### get config
GET http://localhost:8888/member-api/dev

### get encrypt
GET http://localhost:8888/actuator/health

### encrypt
POST http://localhost:8888/encrypt
Content-Type: application/x-www-form-urlencoded

1234

### decrypt
POST localhost:8888/decrypt
Content-Type: application/x-www-form-urlencoded

AQAeDtv5DcgoyuaEtKp4+VkBHqcMmI21aSV5ShWhfIM6nZVhCNUzxZmLji039e7PbIMXLNgEcc90lnr/tZulZbgCJYdOYoYvV8TaI6GUtK8hEXUxOp64igwn8fUgVXOhHAPnqcfxtLAb6O5YXtX2hYEKTycB+q+ySXnusE2fkNDaHltU3mxYvoMO/WGv+Wn6RvODctdLutn8atYBj179fcN1JPakhpmT2i1NkfoqOnhBQROmwVvbyNwaPI7r0ywB+pp0zJHwnHGUiUD0Dn7qwRW5oq60RXsRC69FAUq2a/XIj8X+TLBF39wlVcUT1ex0luaFoo8fU5sRNEUuK9Q0+UdEt+x+tIlKduFZZhXs3aN0l9vTDNf+EeTTOIJHN9eZMng=

###

